### ISSUE TITLE
segmentation fault when making reference index

### ISSUE THREAD

**Issue by jpfeil** [isovic/graphmap#17]
Hi Ivan,

Whenever I run graphmap (v.022), I get a segmentation fault. My computer is running Ubuntu 15.10 with 30GB of RAM and the parsimonious memory mode. 

[Index 14:21:45] Running in parsimonious mode. Only one index will be used.
[Index 14:21:45] Generating index.
Segmentation fault (core dumped)

Do you know what might be causing this error?

Thanks!

Jacob

**Comment by andreas-wilm** [comment]
Hi Jacob,

Could you please share the exact command line arguments and the reference
itself (best: a Url) with us?

Andreas

**Comment by jpfeil** [comment]
Hello Andreas,

  

Here is the command:

  

./bin/Linux-x64/graphmap -I -P -r ../data/ref/hg38.fa  

  

And here is the link to the reference:

  

ftp://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz  

  

Thank you!

  

Jacob

  

> On Jan 15 2016, at 5:24 pm, Andreas Wilm &lt;notifications@github.com&gt;
wrote:  
Hi Jacob,  
  
Could you please share the exact command line arguments and the reference  
itself (best: a Url) with us?  
  
Andreas  
On 16 Jan 2016 06:38, "Jacob Pfeil" &lt;notifications@github.com&gt; wrote:  
  
&gt; Hi Ivan,  
&gt;  
&gt; Whenever I run graphmap (v.022), I get a segmentation fault. My computer  
&gt; is running Ubuntu 15.10 with 30GB of RAM and the parsimonious memory
mode.  
&gt;  
&gt; [Index 14:21:45] Running in parsimonious mode. Only one index will be
used.  
&gt; [Index 14:21:45] Generating index.  
&gt; Segmentation fault (core dumped)  
&gt;  
&gt; Do you know what might be causing this error?  
&gt;  
&gt; Thanks!  
&gt;  
&gt; Jacob  
&gt;  
&gt; —  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/isovic/graphmap/issues/17&gt;.  
&gt;  

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/isovic/
graphmap/issues/17#issuecomment-172142849).![](https://github.com/notification
s/beacon/AL4vVGHvdAlnadv7xPH3V8WzyCgDy7Pyks5paZNKgaJpZM4HGGDz.gif)

**Comment by isovic** [comment]
Hi Jacob!

How much memory do you have installed on the machine?
The index will require about 20x the genome size.

Thanks,
Ivan.

**Comment by jpfeil** [comment]
Hi Ivan,

  

I was not aware that the index needs 20x the genome in memory. Is this also
true for the parsimonious mode? I currently have 30GB of memory and a 3GB
reference, so that is the problem.

  

Thanks,

  

Jacob  

> On Jan 16 2016, at 10:21 am, Ivan Sovic &lt;notifications@github.com&gt;
wrote:  

>

> Hi Jacob!

>

> How much memory do you have installed on the machine?  
The index will require about 20x the genome size.

>

> Thanks,  
Ivan.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/isovic/
graphmap/issues/17#issuecomment-172242067).![](https://github.com/notification
s/beacon/AL4vVHUu0PLHA1OzBhfNt75Da2UUcNsjks5paoGegaJpZM4HGGDz.gif)

**Comment by isovic** [comment]
Unfortunately yes - think of it like this: 64-bit integers are used for coding the positions on the reference which includes both fwd and rev sequences (so 2*8 bytes) + the original fwd sequence + the rev sequence = 18x original sequence length. On top of that goes the perfect hash table which consumes far less though on large references, because of small seed sizes.
So, in total it's about 18x per index (20x was an approximation). In parsimonious mode only one index is used, whereas in the default mode two are used at the same time, making memory consumption even larger (~36x the genome size).

We are currently developing other indexing methods which should reduce this number significantly, but it will take some time before it gets released.

Ivan
