### ISSUE TITLE
compile error: 'pow' is not a member of 'std'

### ISSUE THREAD

**Issue by tolot27** [isovic/graphmap#36]
The build fails on Ubuntu 14.04 on the `src\index\` source files with the error: `'pow' is not a member of 'std'`.

This can be fixed by adding `#include <cmath>` to `src/index/index.h`.

**Comment by isovic** [comment]
Hi, I added the missing header as per your suggestion, you can try ```git pull; make modules; make```. Let me know if it doesn't work.
Best regards,
Ivan.

**Comment by uperetz** [comment]
Tested on Debian Stretch x64:
1. You forgot to "#include <cmath>" - I put it in src/crypt.h, but let me know if there is a more proper place. `std::pow` won't compile otherwise.
2. I suggest in your README to send Linux users to the bottom for the make instruction (so it's clear they need to clone and make release).
3. Consider a make install/make install global/local that copies the bin file to the global/local bin (sudo for global needed).
4. Consider shortening the action: -en,-de. Also you could by default determine if the header is one made by you (nppcrypt) and decrypt automatically or encrypt otherwise.

These are all suggestions (except 1), but bottom line - works great so far! Nice works and a big thanks. This issue should be closed.
